app/oauth/forms.py
from flask_wtf import FlaskForm
from wtforms import FieldList, FormField, StringField, SubmitField, URLField
from wtforms.validators import DataRequired, Length


class RedirectURIForm(FlaskForm):
    class Meta:
        csrf = False

    redirect_uri = URLField(
        "Redirect URI",
        validators=[DataRequired()],
        render_kw={"placeholder": "https://example.com/callback"},
    )


class CreateClientForm(FlaskForm):
    client_name = StringField(
        "App name",
        name="client_name",
        validators=[DataRequired(), Length(min=3, max=32)],
    )
    client_description = StringField(
        "App description", name="client_description", validators=[DataRequired()]
    )
    client_uri = URLField("Website", name="client_uri")
    redirect_uris = FieldList(
        FormField(RedirectURIForm),
        "Redirect URIs",
        min_entries=1,
        max_entries=10,
        validators=[DataRequired()],
    )
    submit = SubmitField("Save")


class ResetClientSecretFrom(FlaskForm):
    reset_secret = SubmitField("Reset Secret")


class DeleteClientForm(FlaskForm):
    delete = SubmitField("Delete")


class EditClientForm(FlaskForm):
    edit = SubmitField("Edit")


class AuthorizeConsentForm(FlaskForm):
    confirm = SubmitField("Allow")
    consent = StringField("Consent", render_kw={"type": "checkbox"})
    username = StringField("Username")

app/oauth/__init__.py
from flask import Blueprint

bp = Blueprint("oauth", __name__)

from app.oauth import routes

app/oauth/routes.py
from datetime import datetime
from time import time

from authlib.oauth2 import OAuth2Error
from flask import abort, flash, redirect, render_template, request, session, url_for
from flask_security import auth_required, current_user, url_for_security
from werkzeug.security import gen_salt

from app.extensions import csrf, db
from app.models import OAuth2Client, User
from app.oauth import bp
from app.oauth.forms import (
    AuthorizeConsentForm,
    CreateClientForm,
    DeleteClientForm,
    EditClientForm,
    ResetClientSecretFrom,
)
from app.oauth.oauth2 import authorization


@bp.route("/dashboard", methods=["GET", "POST"])
@bp.route("/dashboard/<client_id>", methods=["GET", "POST"])
@auth_required()
def dashboard(client_id=None):
    user = User.query.get(current_user.id)

    if user:
        clients = OAuth2Client.query.filter_by(user_id=user.id).all()
    else:
        clients = []

    if client_id:
        client = [client for client in clients if client.client_id == client_id]
        if not client:
            abort(404)

        is_new_client = session.pop("is_new_client", False)
        if not is_new_client:
            client[0].secret_seen = True
            db.session.commit()

        reset_secret_form = ResetClientSecretFrom()
        edit_req_form = EditClientForm()
        delete_req_form = DeleteClientForm()

        if reset_secret_form.validate_on_submit() and "reset_secret" in request.form:
            client[0].client_secret = gen_salt(48)
            client[0].secret_seen = False
            db.session.commit()
            session["is_new_client"] = True

            flash(
                "Client secret reset successfully!",
                "success",
            )
            return redirect(url_for("oauth.dashboard", client_id=client_id))

        if edit_req_form.validate_on_submit() and "edit" in request.form:
            return redirect(url_for("oauth.edit_client", client_id=client_id))

        if delete_req_form.validate_on_submit() and "delete" in request.form:
            client = client[0]
            # Delete all tokens for this client (cascade delete for authorized apps)
            from app.models import OAuth2Token

            OAuth2Token.query.filter_by(client_id=client.client_id).delete()
            db.session.delete(client)
            db.session.commit()
            flash(
                f"Successfully deleted {client.client_metadata['client_name']}!",
                "success",
            )
            return redirect(url_for("oauth.dashboard"))

        if is_new_client:
            flash(
                "Make sure to save the client secret somewhere safe! It will not be shown again.",
                "info",
            )

        return render_template(
            "oauth/client_info.html",
            user=user,
            client=client[0],
            title="Developer Dashboard",
            active_page="dev_dashboard",
            year=datetime.today().year,
            reset_secret_form=reset_secret_form,
            edit_req_form=edit_req_form,
            delete_req_form=delete_req_form,
        )

    return render_template(
        "oauth/dashboard.html",
        user=user,
        clients=clients,
        title="Developer Dashboard",
        active_page="dev_dashboard",
        year=datetime.today().year,
    )


@bp.route("/dashboard/create", methods=["GET", "POST"])
def create_client():
    if not current_user.is_authenticated:
        abort(401)

    user = User.query.get(current_user.id)
    create_client_form = CreateClientForm()
    if create_client_form.validate_on_submit():
        client_id = gen_salt(24)
        client_id_issued_at = int(time())
        client = OAuth2Client(
            client_id=client_id,
            client_id_issued_at=client_id_issued_at,
            user_id=user.id,
        )

        client_metadata = {
            "client_name": create_client_form.client_name.data,
            "client_description": create_client_form.client_description.data,
            "client_uri": create_client_form.client_uri.data or "None",
            "grant_types": ["authorization_code", "refresh_token"],
            "redirect_uris": [
                data.get("redirect_uri")
                for data in create_client_form.redirect_uris.data
            ],
            "response_types": ["code"],
            "scope": "activity",
            "token_endpoint_auth_method": "client_secret_basic",
        }
        client.set_client_metadata(client_metadata)
        client.client_secret = gen_salt(48)

        db.session.add(client)
        db.session.commit()
        flash(
            f'Successfully created "{create_client_form.client_name.data}"!', "success"
        )

        session["is_new_client"] = True
        return redirect(url_for("oauth.dashboard", client_id=client_id))

    return render_template(
        "oauth/create_client.html",
        title="Developer Dashboard",
        active_page="create_client",
        create_client_form=create_client_form,
        year=datetime.today().year,
    )


@bp.route("/dashboard/<client_id>/edit", methods=["GET", "POST"])
@auth_required()
def edit_client(client_id):
    user = User.query.get(current_user.id)
    client = OAuth2Client.query.filter_by(client_id=client_id).first()
    if not client or client.user_id != user.id:
        abort(404)

    client_metadata = client.client_metadata.copy()
    redirect_uris_data = [
        {"redirect_uri": uri} for uri in client_metadata.get("redirect_uris", [])
    ]

    if request.method == "GET":
        edit_client_form = CreateClientForm(
            client_name=client_metadata.get("client_name", ""),
            client_description=client_metadata.get("client_description", ""),
            client_uri=client_metadata.get("client_uri", ""),
            redirect_uris=redirect_uris_data,
        )
    else:
        edit_client_form = CreateClientForm()

    if edit_client_form.validate_on_submit():
        client.set_client_metadata(
            {
                "client_name": edit_client_form.client_name.data,
                "client_description": edit_client_form.client_description.data,
                "client_uri": edit_client_form.client_uri.data,
                "grant_types": ["authorization_code", "refresh_token"],
                "redirect_uris": [
                    data.get("redirect_uri")
                    for data in edit_client_form.redirect_uris.data
                ],
                "response_types": ["code"],
                "scope": "activity",
                "token_endpoint_auth_method": "client_secret_basic",
            }
        )
        db.session.commit()
        flash("Successfully updated the App information!", "success")
        return redirect(url_for("oauth.dashboard", client_id=client_id))

    return render_template(
        "oauth/edit_client.html",
        client=client,
        title="Developer Dashboard",
        active_page="dev_dashboard",
        year=datetime.today().year,
        edit_client_form=edit_client_form,
    )


@bp.route("/authorize", methods=["GET", "POST"])
def authorize():
    try:
        user = User.query.get(current_user.id)
    except AttributeError:
        return redirect(url_for_security("login", next=request.url))

    form = AuthorizeConsentForm()
    if request.method == "GET":
        try:
            grant = authorization.get_consent_grant(end_user=user)
        except OAuth2Error as error:
            return error.error
        return render_template(
            "oauth/authorize.html", user=user, grant=grant, form=form
        )
    if not user and "username" in request.form:
        username = request.form.get("username")
        user = User.query.filter_by(username=username).first()
    # Handle Deny button
    if request.form.get("confirm") == "no":
        # Return OAuth2 error response for access_denied
        return authorization.create_authorization_response(grant_user=None)
    # Handle Allow button
    if form.validate_on_submit() and request.form.get("confirm") == "yes":
        grant_user = user
    else:
        grant_user = None
    return authorization.create_authorization_response(grant_user=grant_user)


@csrf.exempt
@bp.route("/api/token", methods=["POST"])
def issue_token():
    return authorization.create_token_response()


@csrf.exempt
@bp.route("/api/revoke", methods=["POST"])
def revoke_token():
    return authorization.create_endpoint_response("revocation")

app/templates/oauth/authorize.html
{% set title = 'Authorize ' + grant.client.client_name + ' ?' %}
{% extends "base.html" %}

{% block nav_title %}
{{ title }}
{% endblock %}

{% block header %}
<header class="container">
    <h1 id="header-title">{{ title }}</h1>
</header>
{% endblock %}

{% block content %}
<main class="container">
    <article class="custom-article margin-btm">
        <p>You are logged in as:</p>
        <div class="flex-row left">
            <img class="profile-header-img small" src="{{ url_for('static', filename=user.avatar) }}" alt="User Avatar"
                width="64px" height="64px">

            <div>
                <strong>{{ user.name }}</strong>
                <small>@{{ user.username }}</small>
            </div>

            <a
                href="{{ url_for_security('logout', next=url_for('security.login', next=request.url, _external=True)) }}">Not
                You?</a>
        </div>
    </article>
    <article class="custom-article">
        <p>The application <a href="{{ grant.client.client_uri }}"><strong>{{ grant.client.client_name }}</strong></a> is requesting access to your account:</p>
        <div class="flex-row left" style="margin-bottom: 1rem;">
            <strong>
                {% if grant.request.scope == 'activity' %}
                <dl>
                    <dt>
                        <i class="fa-solid fa-headphones-simple"></i>
                        Activity
                    </dt>
                    <dd>View your listening activity on your linked services.</dd>
                </dl>

                {% else %}
                <i class="fa-solid fa-question"></i>
                Unknown permission requested
                {% endif %}
            </strong>
        </div>
        <small>You can remove this access at any time in your account settings.</small>
        <form method="post">
            {{ form.hidden_tag() }}
            <fieldset>
                {% if not user %}
                <p>You haven't logged in. Log in with:</p>
                <div>
                    {{ form.username(placeholder="Username") }}
                </div>
                {% endif %}
            </fieldset>
            <div class="flex-row space-between">
                <button type="submit" name="confirm" value="yes" class="primary">Allow</button>
                <button type="submit" name="confirm" value="no" class="secondary">Deny</button>
            </div>
        </form>
    </article>
</main>
{% endblock %}

app/templates/oauth/client_info.html
{% set title = 'App Information' %}
{% extends "base.html" %}

{% block nav_title %}
{{ title }}
{% endblock %}

{% block header %}
<header class="container">
    <h1 id="header-title">{{ title }}</h1>
</header>
{% endblock %}

{% block content %}
<main class="container">
    <article class="client-card margin-btm info">
        <div class="flex-row left">
            <span>
                <h6>Client ID</h6>
                <code>{{ client.client_info["client_id"] }}</code>
            </span>
            <span>
                <h6>Client Secret</h6>
                {% if not client.secret_seen %}
                <code>{{ client.client_info["client_secret"] }}</code>
                {% else %}
                <code class="client-secret-seen">
                    <span>Hidden for security.</span>
                    {{ reset_secret_form.reset_secret(class="custom-fixed-width-btn", form="reset_secret_form") }}
                </code>
                {% endif %}
            </span>
        </div>
    </article>

    <article class="client-card info">
        <div class="margin-btm">
            <h6 class="no-margin-btm">Name</h6>
            <code>{{ client.client_metadata["client_name"] }}</code>
        </div>
        <div class="margin-btm">
            <h6 class="no-margin-btm">Description</h6>
            <code>{{ client.client_metadata["client_description"] }}</code>
        </div>
        <div class="margin-btm">
            <h6 class="no-margin-btm">Website</h6>
            <code>{{ client.client_metadata["client_uri"] }}</code>
        </div>
        <div class="margin-btm">
            <h6 class="no-margin-btm">Redirect URIs</h6>
            <code>
                {% for uri in client.client_metadata["redirect_uris"] %}
                <li>{{ uri }}</li>
                {% endfor %}
            </code>
        </div>
    </article>
    <form action="" method="post" id="reset_secret_form">
        {{ reset_secret_form.csrf_token(id="reset_secret_form") }}
    </form>
    <form action="" method="post" id="edit_client_form">
        {{ edit_req_form.csrf_token(id="csrf_token_edit") }}
    </form>
    <form action="" method="post" id="delete_client_form">
        {{ delete_req_form.csrf_token(id="csrf_token_delete") }}
    </form>

    <div class="flex-row left">
        {{ edit_req_form.edit(class="custom-fixed-width-btn", form="edit_client_form") }}
        {{ delete_req_form.delete(class="custom-fixed-width-btn secondary delete-btn", form="delete_client_form") }}
    </div>
</main>
{% endblock %}

app/templates/oauth/create_client.html
{% extends "base.html" %}

{% block content %}
<main class="container">
  <form action="" method="post">
    {{ create_client_form.hidden_tag() }}
    <fieldset>
      {{ create_client_form.client_name.label }}
      {% if create_client_form.client_name.errors %}
      {{ create_client_form.client_name(autofocus="", aria_label="Client Name", aria_describedby="client-name-helper", aria_invalid="true") }}
      {% else %}
      {{ create_client_form.client_name(autofocus="", aria_label="Client Name", aria_describedby="client-name-helper") }}
      {% endif %}
      {% for error in create_client_form.client_name.errors %}
      <small id="client-name-helper">{{ error }}</small>
      {% endfor %}

      {{ create_client_form.client_description.label }}
      {% if create_client_form.client_description.errors %}
      {{ create_client_form.client_description(autofocus="", aria_label="Client Description", aria_describedby="client-description-helper", aria_invalid="true") }}
      {% else %}
      {{ create_client_form.client_description(autofocus="", aria_label="Client Description", aria_describedby="client-description-helper") }}
      {% endif %}
      {% for error in create_client_form.client_description.errors %}
      <small id="client-description-helper">{{ error }}</small>
      {% endfor %}

      {{ create_client_form.client_uri.label }}
      {% if create_client_form.client_uri.errors %}
      {{ create_client_form.client_uri(autofocus="", aria_label="Website", aria_describedby="website-helper", aria_invalid="true") }}
      {% else %}
      {{ create_client_form.client_uri(autofocus="", aria_label="Website", aria_describedby="website-helper") }}
      {% endif %}
      {% for error in create_client_form.client_uri.errors %}
      <small id="website-helper">{{ error }}</small>
      {% endfor %}

      <p>Redirect URIs</p>
      <div id="redirectURIs">
        {% for redirect_uri in create_client_form.redirect_uris.entries %}
        <div class="redirectURI">
          <span class="remove-redirect_uri"><i class="fa-solid fa-xmark"></i></span>
          {% if redirect_uri.form.redirect_uri.errors %}
          {{ redirect_uri.form.redirect_uri(autofocus="", aria_label="Redirect URI", aria_describedby="redirect-uri-helper redirect-uri-helper-two", aria_invalid="true") }}
          {% else %}
          {{ redirect_uri.form.redirect_uri(aria_label="Redirect URI", aria_describedby="redirect-uri-helper redirect-uri-helper-two") }}
          {% endif %}
          {% for error in redirect_uri.form.redirect_uri.errors %}
          <small id="redirect-uri-helper">{{ error }}</small>
          {% endfor %}
        </div>
        {% endfor %}
      </div>
      <small class="invalid" id="redirect-uri-helper-two"></small>
      <input class="custom-inp-btn" id="add-redirect-uri" type="button" value="Add Another Redirect URI" disabled>
    </fieldset>
    {{ create_client_form.submit }}
  </form>
</main>
{% endblock %}

app/templates/oauth/dashboard.html
{% extends "base.html" %}

{% block nav_title %}
{{ title }}
{% endblock %}

{% block header %}
<header class="container">
  <h1 id="header-title">{{ title }}</h1>
</header>
{% endblock %}

{% block content %}
<main class="container">
  <div class="client-container">

    <a class="client-container-btn" href="{{ url_for('oauth.create_client') }}">
      <button>Create App</button>
    </a>

    {% if clients %}
    {% for client in clients %}
    <a class="client-card-link" href="{{ url_for('oauth.dashboard', client_id=client.client_info['client_id']) }}">
      <article class="client-card no-margin-btm">
        <div class="flex-row left client-info">
          <div class="client-img">
            <span>{{ client.client_metadata["client_name"][0] }}</s>
          </div>
          <div>
            <h3 class="no-margin-btm">{{ client.client_metadata["client_name"] }}</h3>
            <small class="client-desc">{{ client.client_metadata["client_description"] }}</small>
          </div>
        </div>
      </article>
    </a>
    {% endfor %}
    {% else %}
      <p class="text-in-article">You haven't created any apps yet. Create one by clicking the above button!</p>
    {% endif %}
  </div>
</main>
{% endblock %}

app/templates/oauth/edit_client.html
{% set title = 'Edit App Information' %}
{% extends "base.html" %}

{% block nav_title %}
{{ title }}
{% endblock %}

{% block header %}
<header class="container">
    <h1 id="header-title">{{ title }}</h1>
</header>
{% endblock %}

{% block content %}
<main class="container">
    <form action="" method="post">
        {{ edit_client_form.hidden_tag() }}
        <fieldset>
            {{ edit_client_form.client_name.label }}
            {% if edit_client_form.client_name.errors %}
            {{ edit_client_form.client_name(autofocus="", aria_label="Client Name", aria_describedby="client-name-helper", aria_invalid="true") }}
            {% else %}
            {{ edit_client_form.client_name(autofocus="", aria_label="Client Name", aria_describedby="client-name-helper") }}
            {% endif %}
            {% for error in edit_client_form.client_name.errors %}
            <small id="client-name-helper">{{ error }}</small>
            {% endfor %}

            {{ edit_client_form.client_description.label }}
            {% if edit_client_form.client_description.errors %}
            {{ edit_client_form.client_description(autofocus="", aria_label="Client Description", aria_describedby="client-description-helper", aria_invalid="true") }}
            {% else %}
            {{ edit_client_form.client_description(autofocus="", aria_label="Client Description", aria_describedby="client-description-helper") }}
            {% endif %}
            {% for error in edit_client_form.client_description.errors %}
            <small id="client-description-helper">{{ error }}</small>
            {% endfor %}

            {{ edit_client_form.client_uri.label }}
            {% if edit_client_form.client_uri.errors %}
            {{ edit_client_form.client_uri(autofocus="", aria_label="Website", aria_describedby="website-helper", aria_invalid="true") }}
            {% else %}
            {{ edit_client_form.client_uri(autofocus="", aria_label="Website", aria_describedby="website-helper") }}
            {% endif %}
            {% for error in edit_client_form.client_uri.errors %}
            <small id="website-helper">{{ error }}</small>
            {% endfor %}

            <p>Redirect URIs</p>
            <div id="redirectURIs">
                {% for redirect_uri in edit_client_form.redirect_uris.entries %}
                <div class="redirectURI">
                    <span class="remove-redirect_uri"><i class="fa-solid fa-xmark"></i></span>
                    {% if redirect_uri.redirect_uri.errors %}
                    {{ redirect_uri.redirect_uri(autofocus="", aria_label="Redirect URI", aria_describedby="redirect-uri-helper", aria_invalid="true") }}
                    {% else %}
                    {{ redirect_uri.redirect_uri(aria_label="Redirect URI", aria_describedby="redirect-uri-helper") }}
                    {% endif %}
                    {% for error in redirect_uri.redirect_uri.errors %}
                    <small id="redirect-uri-helper">{{ error }}</small>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
            <input class="custom-inp-btn" id="add-redirect-uri" type="button" value="Add Another Redirect URI" disabled>
        </fieldset>
        {{ edit_client_form.submit }}
    </form>
</main>
{% endblock %}