app/docs/__init__.py
from flask import Blueprint

bp = Blueprint("docs", __name__)

from app.docs import routes

app/docs/routes.py
from datetime import datetime

from flask import render_template, request, url_for

from app.docs import bp


@bp.route("/")
@bp.route("")
def index():
    """Render the API documentation page."""
    base_url = url_for("main.index", _external=True).rstrip("/")
    return render_template(
        "docs/overview.html",
        title="Overview",
        active_page="docs",
        aside_active="Overview",
        base_url=base_url,
        year=datetime.today().year,
    )


@bp.route("/get-started")
def get_started():
    """Render the "Get Started" page in the API documentation page."""
    base_url = url_for("main.index", _external=True).rstrip("/")
    return render_template(
        "docs/get_started.html",
        title="Get Started",
        active_page="docs",
        aside_active="Get Started",
        base_url=base_url,
        year=datetime.today().year,
    )


@bp.route("/concepts/<concept>")
@bp.route("/concepts")
def concepts(concept=None):
    """Render the "Concepts" page in the API documentation page."""
    match concept:
        case "apps":
            return render_template(
                "docs/concepts/apps.html",
                title="Concepts - Apps",
                active_page="docs",
                aside_active="Concepts",
                year=datetime.today().year,
            )
        case "tokens":
            return render_template(
                "docs/concepts/tokens.html",
                title="Concepts - Tokens",
                active_page="docs",
                aside_active="Concepts",
                year=datetime.today().year,
            )
        case "activity":
            return render_template(
                "docs/concepts/activity.html",
                title="Concepts - Activity",
                active_page="docs",
                aside_active="Concepts",
                year=datetime.today().year,
            )
        case _:
            # Default case for the main concepts page
            return render_template(
                "docs/concepts.html",
                title="Concepts",
                active_page="docs",
                aside_active="Concepts",
                year=datetime.today().year,
            )


@bp.route("/tutorials/<tutorial>")
@bp.route("/tutorials")
def tutorials(tutorial=None):
    """Render the "Tutorials" page in the API documentation page."""
    base_url = url_for("main.index", _external=True).rstrip("/")
    match tutorial:
        case "authorization-guide":
            return render_template(
                "docs/tutorials/authorization_guide.html",
                title="Tutorials - Authorization Guide",
                active_page="docs",
                aside_active="Tutorials",
                base_url=base_url,
                year=datetime.today().year,
            )
        case _:
            return render_template(
                "docs/tutorials.html",
                title="Tutorials",
                active_page="docs",
                aside_active="Tutorials",
                year=datetime.today().year,
            )


@bp.route("/references/<reference>")
def references(reference):
    """Render the API reference pages based on the provided reference type."""
    base_url = url_for("main.index", _external=True).rstrip("/")
    match reference:
        case "activity":
            return render_template(
                "docs/references/activity.html",
                title="API Reference Activity",
                active_page="docs",
                aside_active="Activity",
                base_url=base_url,
                year=datetime.today().year,
            )
        case "search":
            return render_template(
                "docs/references/search.html",
                title="API Reference Search",
                active_page="docs",
                aside_active="Search",
                base_url=base_url,
                year=datetime.today().year,
            )
        case _:
            # Return a 404 page if the reference is not found
            return render_template("404.html"), 404

app/templates/docs/base.html
{% extends "base.html" %}
{% block metadata %}
<meta property="og:url" content="{{ url_for('docs.index', _external=true) }}">
<meta property="og:type" content="website">
<meta property="og:title" content="{{ config['SERVICE'] }}: API Documentation">
<meta property="og:description"
    content="Read the docs for {{ config['SERVICE'] }}, simple RESTful API for retrieving music info for various steaming platforms.">
<meta property="og:image" content="{{ url_for('static', filename='music.png', _external=true) }}">
<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="{{ config['HOST_URL'] }}">
<meta property="twitter:url" content="{{ url_for('docs.index', _external=true) }}">
<meta name="twitter:title" content="{{ config['HOST_URL'] }}: API Documentation">
<meta name="twitter:description"
    content="Read the docs for {{ config['SERVICE'] }}, simple RESTful API for retrieving music info for various steaming platforms.">
<meta name="twitter:image" content="{{ url_for('static', filename='music.png', _external=true) }}">
{% endblock %}

{% block style %}
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/tokyo-night-dark.min.css"
    integrity="sha512-dSQLLtgaq2iGigmy9xowRshaMzUHeiIUTvJW/SkUpb1J+ImXOPNGAI7ZC8V5/PiN/XN83B8uIk4qET7AMhdC5Q=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block nav_title %}
{{ title }}
{% endblock %}

{% block header %}
<header class="container">
    <h1 id="header-title">{{ title }}</h1>
    <p class="warning">The Docs are work-in-progress except API References!</p>
</header>
{% endblock %}

{% block content %}
<section class="sect-with-aside">
    <aside class="top">
        <nav id="aside-nav">
            <ul>
                <li class="{% if aside_active == 'Overview' %}aside-active{% endif %}">
                    <a href="{{ url_for('docs.index') }}">Overview</a>
                </li>
                <li class="{% if aside_active == 'Get Started' %}aside-active{% endif %}">
                    <a href="{{ url_for('docs.get_started') }}">Get Started</a>
                </li>
                <li class="{% if aside_active == 'Concepts' %}aside-active{% endif %}">
                    <a href="{{ url_for('docs.concepts') }}">Concepts</a>
                </li>
                <li class="{% if aside_active == 'Tutorials' %}aside-active{% endif %}">
                    <a href="{{ url_for('docs.tutorials') }}">Tutorials</a>
                </li>
                <li>REFERENCE</li>
                <li class="{% if aside_active == 'Search' %}aside-active{% endif %}">
                    <a href="{{ url_for('docs.references', reference='search') }}">Search</a>
                </li>
                <li class="{% if aside_active == 'Activity' %}aside-active{% endif %}">
                    <a href="{{ url_for('docs.references', reference='activity') }}">Activity</a>
                </li>
            </ul>
        </nav>
    </aside>
    {% block main %}{% endblock %}
</section>
{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"
    integrity="sha512-EBLzUL8XLl+va/zAsmXwS7Z2B1F9HUHkZwyS/VKwh3S7T/U0nF4BaU29EP/ZSf6zgiIxYAnKLu6bJ8dqpmX5uw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{{ url_for('static', filename='scripts/docs.js') }}"></script>
{% endblock %}

app/templates/docs/concepts.html
{% extends "docs/base.html" %}

{% block main %}
<main class="container">
    <ul>
        <li>
            <a href="{{ url_for('docs.concepts', concept='apps') }}">Apps</a>: Apps allow you to access protected
            endpoints like
            <a href="{{ url_for('docs.references', reference='activity')}}">Activity</a>.
        </li>
        <li>
            <a href="{{ url_for('docs.concepts', concept='tokens') }}">Tokens</a>: Tokens are used to authenticate your
            app and access protected endpoints.
        </li>
        <li>
            <a href="{{ url_for('docs.concepts', concept='activity') }}">Activity</a>: The metadata / information about
            a user's currently listening music on a linked service(s).
        </li>
    </ul>
</main>
{% endblock %}

app/templates/docs/concepts_activity.html
{% extends "docs/base.html" %}

{% block main %}
<main class="container">
    <p>
        The metadata / information about a user's currently listening music on a linked service(s).
        This guide explains how to link a service to your account and access your activity data.
    </p>

    <p>
        To link a service to your account, first <a href="{{ url_for_security('login') }}">Login</a> or <a
            href="{{ url_for_security('register') }}">Sign Up</a>.
        Then, go to your {% if current_user.is_authenticated %} <a
            href="{{ url_for('user.user_settings', username=current_user.username) }}">Settings</a>{% else %} "Settings"
        {%
        endif %} page and scroll to the "Services" section. Now click on the "Link" button next to the service you want
        to link and follow the instructions.
        <img src="{{ url_for('static', filename='docs/settings-page.png') }}" alt="Settings Screenshot"
            class="screenshot">
    </p>
    <p>
        After successfully linking a service, you will be redirected back to the settings page where you can see the
        linked service. And for this example, I linked my Spotify account:
        <img src="{{ url_for('static', filename='docs/settings-linked-spotify.png') }}" alt="Settings Screenshot"
            class="screenshot">
    </p>
    <p>
        Now that you have linked a service, listen to some music on that service and then go to your {% if
        current_user.is_authenticated %}<a
            href="{{ url_for('user.user_profile', username=current_user.username) }}">Profile</a>{% else %}"Profile"{%
        endif %} page, you should see the metadata about your currently listening music:
        <img src="{{ url_for('static', filename='docs/user-profile-activity.png') }}" alt="Profile Screenshot"
            class="screenshot">
    </p>
    <p>
        You can also access your activity data by making a request to the <code>/api/me</code> endpoint.
        This endpoint will return the metadata of your currently listening music on the linked service(s).
    </p>
</main>
{% endblock %}

app/templates/docs/concepts_apps.html
{% extends "docs/base.html" %}

{% block main %}
<main class="container">
    <p>
        <strong>Apps</strong> allow you to access protected endpoints like
        <a href="{{ url_for('docs.reference_activity')}}">Activity</a>. This guide explains how to create and manage
        apps.
    </p>

    <p>
        To create an app, go to your <a href="{{ url_for('oauth.dashboard') }}">Dashboard</a> and click on "Create
        App" button.
        <img src="{{ url_for('static', filename='docs/dashboard.png') }}" alt="Dashboard Screenshot" class="screenshot">
    </p>
    <p>
        Then fill in the details for your app:
    <ul>
        <li><strong>App Name:</strong> A unique name for your app.</li>
        <li><strong>App Description:</strong> A brief description of what your app does.</li>
        <li><strong>Website</strong> [OPTIONAL]: A URL to website where users can get more information about your
            application.</li>
        <li><strong>Redirect URIs:</strong> The URL where users will be redirected after authorizing your app.
            This is where you will receive the authorization code. You can add multiple redirect URIs if needed.
    </ul>
    <img src="{{ url_for('static', filename='docs/dashboard-create-app-filled.png') }}" alt="Dashboard Screenshot"
        class="screenshot">
    </p>
    <p>
        After creating the app, you will receive a <strong>Client ID</strong> and <strong>Client Secret</strong>.
        Keep
        these safe as they are used to authenticate your app.
        <img src="{{ url_for('static', filename='docs/dashboard-app-info.png') }}" alt="Dashboard Screenshot"
            class="screenshot">

    </p>
    <p>
        Your app is now created and you can use the Client ID and Client Secret to authenticate your app with the yutify
        API.
    </p>
    <p>
        If you want to edit your app details, you can do so by clicking on the "Edit" button next to your app in the
        dashboard. And if you want to delete your app, you can click on the "Delete" button.
    </p>
</main>
{% endblock %}

app/templates/docs/get_started.html
{% extends "docs/base.html" %}

{% block main %}
<main class="container">
    <p>
        Welcome, this guide will walk you through how to use <strong>{{ config["SERVICE"] }}</strong> to retrieve music
        information from various streaming platforms as well as how to request your listening activity data by calling
        OAuth 2.0 protected endpoints.
    </p>

    <h2>Search for Music</h2>

    <h3>Prerequisites</h3>
    <ul>
        <li>
            Make sure your are familier working with CLI (Command Line Interface).
        </li>
        <li>
            We will be using <strong>cURL</strong> for making API requests, so make sure you have it installed on your
            system. But you can also use any HTTP client of your choice.
            You may download it from <a href="https://curl.se/download.html">here</a> and scroll down to find
            download for your operating system. Or you can use package manager came with your OS to install it.
        </li>
    </ul>

    <p>
        We can use the <a href="{{ url_for('docs.references', reference='search') }}">Search</a> endpoint
        to find music information. You just need to provide the artist and song or album name.
        So, let's search for "<i>Shelter</i>" by "<i>Porter Robinson</i>". We will make a GET request to the
        <code>/api/search</code> endpoint like this:
    <pre><code class="language-bash">curl -X GET "{{ base_url }}/api/search/Porter%20Robinson:Shelter"</code></pre>
    </p>
    <blockquote>
        Notice we are not using query parameters to search for music, instead we are using a path parameter
        to pass the search query. And a colon (<code>:</code>) is used to separate the artist and song name in the URL.
        This is how the API is designed and the primary reason for this is to avoid issues with
        special characters in the query string. For example, if the song or artist name contains a slash
        (<code>/</code>), it is misunderstood as a path separator when using query parameters.
    </blockquote>
    <p>If everything goes well, the API will return the a JSON response with the metadata about requested music.</p>

    <blockquote>&#10024; Congratulations, you just used the search endpoint to retrieve music information!</blockquote>

    <h3>What's Next?</h3>
    <p>
        You can explore the <a href="{{ url_for('docs.references', reference='search') }}">Search Reference</a>
        for more details on how to use the search endpoint, including how to retrieve music information from a specific
        streaming platform by using the <code>platform</code> query parameter.
    </p>

    <hr>

    <h2>Retrieve Listening Activity</h2>
    <p>
        To retrieve a user's listening activity, we need to use the
        <a href="{{ url_for('docs.references', reference='activity') }}">Activity</a> endpoint.
    </p>

    <ul>
        <li><strong>Create an Account</strong>: If you haven't already, you need to create an account on the
            <strong>{{ config["SERVICE"] }}</strong>.
            Go to <a href="{{ url_for_security('register', next=request.url) }}">Sign Up</a> page and create an account.
        </li>
        <li><strong>Link a Service</strong>: After creating an account and/or logging in, Follow the <a
                href="{{ url_for('docs.concepts', concept='activity') }}">Activity</a> guide to link a service to
            your account.</li>
        <li>Now go to the <a href="{{ base_url }}/api/me"><code>/api/me</code></a> route in your browser.</li>
    </ul>

    <blockquote>
        &#10024; Congratulations, if you are listening to music on a linked service, you will see metadata about your
        current listening activity
        in JSON format!
    </blockquote>

    <h3>What's Next?</h3>
    <p>
        You can explore the <a href="{{ url_for('docs.references', reference='activity') }}">Activity Reference</a>.
    </p>
</main>
{% endblock %}

app/templates/docs/index.html
{% extends "docs/base.html" %}

{% block main %}
<main class="container">
    <p>
        <strong>{{ config["SERVICE"] }}</strong> is a simple RESTful API for retrieving music info from various streaming platforms.
        Using the artist and song name, you can get various information/metadata about the song, including streaming
        link for multiple music platforms.
        If you sign up for an account, you can get music information about your currently listening music as well.
    </p>
    <p>
        The following music streaming platforms are available to get music information/metadata from:
    </p>
    <ul>
        <li><a href="https://music.apple.com" rel="noopener noreferrer" target="_blank">Apple Music</a></li>
        <li><a href="https://deezer.com" rel="noopener noreferrer" target="_blank">Deezer</a></li>
        <li><a href="https://kkbox.com" rel="noopener noreferrer" target="_blank">KKBox</a></li>
        <li><a href="https://open.spotify.com" rel="noopener noreferrer" target="_blank">Spotify</a></li>
        <li><a href="https://music.youtube.com" rel="noopener noreferrer" target="_blank">YouTube Music</a></li>
    </ul>
    <p>
        The following music streaming platforms are available to get currently listening music information:
    </p>
    <ul>
        <li><a href="https://www.last.fm" rel="noopener noreferrer" target="_blank">Lastfm</a></li>
        <li><a href="https://open.spotify.com" rel="noopener noreferrer" target="_blank">Spotify</a></li>
    </ul>

    <h3>Quick Start</h3>
    <p>
        Can't wait to make your first API call? Well, you don't have to!
        The following steps will show you how to make an API call to
        <a href="{{ url_for('docs.reference_search') }}"><code>search</code></a>
        endpoint from your web browser:
    </p>
    <ol>
        <li>
            The endpoint to search for music is: <code>/api/search/&lt;artist&gt;:&lt;song&gt;</code>
            <ul>
                <li>
                    Notice a colon (<code>:</code>) in between artist and song name? We are not using query
                    parameters to search for music.
                </li>
            </ul>
        </li>
        <li>
            Suppose you want to search for "Song" by "Artist".
            The endpoint will look like this:
            <ul>
                <li>
                    <code>/api/search/Artist:Song</code>
                </li>
            </ul>
        </li>
        <li>
            So, here's what the complete URL will look like. Open it in a new tab (or just click on it):
            <ul>
                <li>
                    <a href="{{ base_url }}/api/search/Artist:Song" target="_blank">
                        <code>{{ base_url }}/api/search/Artist:Song</code>
                    </a>
                </li>
            </ul>
        </li>
    </ol>
    <blockquote>&#10024; Congratulations, you just retrieved music information using <strong>{{ config["SERVICE"] }}</strong>!
    </blockquote>
    <p>
        And with that opens endless possibilities for what you can do with it.. If not sure, you may check
        <a href="{{ url_for('docs.tutorials') }}">tutorials</a> for some inspirations and step-by-step guides.
        Or already got something in mind? Check the <a href="{{ url_for('docs.reference_search') }}">API Reference</a>
        for <code>search</code> endpoint!
    </p>
</main>
{% endblock %}

app/templates/docs/overview.html
{% extends "docs/base.html" %}

{% block main %}
<main class="container">
    <p>
        <strong>{{ config["SERVICE"] }}</strong> is a simple RESTful API for retrieving music info from various streaming platforms.
        Using the artist and song name, you can get various information/metadata about the song, including streaming
        link for multiple music platforms.
        If you sign up for an account, you can get music information about your currently listening music as well.
    </p>
    <p>
        The following music streaming platforms are available to get music information/metadata from:
    </p>
    <ul>
        <li><a href="https://music.apple.com" rel="noopener noreferrer" target="_blank">Apple Music</a></li>
        <li><a href="https://deezer.com" rel="noopener noreferrer" target="_blank">Deezer</a></li>
        <li><a href="https://kkbox.com" rel="noopener noreferrer" target="_blank">KKBox</a></li>
        <li><a href="https://open.spotify.com" rel="noopener noreferrer" target="_blank">Spotify</a></li>
        <li><a href="https://music.youtube.com" rel="noopener noreferrer" target="_blank">YouTube Music</a></li>
    </ul>
    <p>
        The following music streaming platforms are available to get currently listening music information:
    </p>
    <ul>
        <li><a href="https://www.last.fm" rel="noopener noreferrer" target="_blank">Lastfm</a></li>
        <li><a href="https://open.spotify.com" rel="noopener noreferrer" target="_blank">Spotify</a></li>
    </ul>

    <h3>Quick Start</h3>
    <p>
        Can't wait to make your first API call? Well, you don't have to!
        The following steps will show you how to make an API call to
        <a href="{{ url_for('docs.references', reference='search') }}"><code>search</code></a>
        endpoint from your web browser:
    </p>
    <ol>
        <li>
            The endpoint to search for music is: <code>/api/search/&lt;artist&gt;:&lt;song&gt;</code>
            <ul>
                <li>
                    Notice a colon (<code>:</code>) in between artist and song name? We are not using query
                    parameters to search for music.
                </li>
            </ul>
        </li>
        <li>
            Suppose you want to search for "Song" by "Artist".
            The endpoint will look like this:
            <ul>
                <li>
                    <code>/api/search/Artist:Song</code>
                </li>
            </ul>
        </li>
        <li>
            So, here's what the complete URL will look like. Open it in a new tab (or just click on it):
            <ul>
                <li>
                    <a href="{{ base_url }}/api/search/Artist:Song" target="_blank">
                        <code>{{ base_url }}/api/search/Artist:Song</code>
                    </a>
                </li>
            </ul>
        </li>
    </ol>
    <blockquote>&#10024; Congratulations, you just retrieved music information using <strong>{{ config["SERVICE"] }}</strong>!
    </blockquote>
    <p>
        And with that opens endless possibilities for what you can do with it.. If not sure, you may check
        <a href="{{ url_for('docs.tutorials') }}">tutorials</a> for some inspirations and step-by-step guides.
        Or already got something in mind? Check the <a href="{{ url_for('docs.references', reference='search') }}">API Reference</a>
        for <code>search</code> endpoint!
    </p>
</main>
{% endblock %}

app/templates/docs/tutorials.html
{% extends "docs/base.html" %}

{% block main %}
<main class="container">
    <p>
        Welcome to the tutorials section! Here, you will find step-by-step guides on how to use <strong>{{ config["SERVICE"] }}</strong> effectively.
        Each tutorial covers a specific aspect of the service, from basic usage to advanced features.
    </p>

    <ul>
        <li><a href="{{ url_for('docs.tutorials', tutorial='authorization-guide') }}">Authorization Guide</a></li>
    </ul>

</main>
{% endblock %}